# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: '55log'
url:   http://log.the55.net
author: 
  name:    the55        # For copyright notice and ATOM feeds
  email:   55@the55.net # Exception emails will go here, and it is used in ATOM feeds
  open_id:                  # These are used to login to the admin area
      - http://the55.livejournal.com
      - http://secondaryopenid.com

